#AntiLogOff Settings.
#Guide: teamld.github.io/alo/

settings:
  timer-duration: 15
  punish-on-logoff: true
  punishment: "kill"  # kill/damage/ban/none
  bossbar-color: "RED"  # RED, PINK, BLUE, GREEN, YELLOW, PURPLE, WHITE, CUSTOM_RGB

  # For CUSTOM_RGB color
  bossbar-rgb:
    red: 255
    green: 0
    blue: 0

messages:
  combat-start: "&cYou entered combat! Don't log out for %time% seconds."
  combat-end: "&aCombat timer expired. You can now log out safely."
  bossbar-text: "&4Combat: %time%s | Don't log out!"
  punished-message: "&cYou were punished for combat logging!"